# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ddB35EhVqtabzPDQ6Mb3OpFr98aYD7yQ
"""

a=[1,3,5,2,7,4,8,9,5,3,5,7,9,3,2,0]
a1=[]

for i in range(len(a)-2):
    sum=a[i]+a[i+1]+a[i+2]
    a1.append(sum)

print(max(a1))



a=[1,3,5,2,7,4,8,9,5,3,5,7,9,3,2,0]
#a=[3,5,7,1,5,8,7,9]
sum=0
max=0
n=int(input("enter the no."))
x=n-1
for i in range(len(a)-n+1):
    for j in range(n):

        sum=a[i+j]+sum
    if(sun>max):
        max=sum
    sum=0
print(max)


a=[]
n=int(input())
k=int(input())
for x in range(0,n):
  ele=int(input())
  a.append(ele)
lt=len(a)
for i in range(0,n-k+1):
  b=[]
  for j in range(i,k+i):
    b.append(a[j])
  print(b)
  print(max(b))



str="ABCBBACBAABACBABC"
pat="CBA"
for i in range(len(str)):
    if(str[i:i+3]==pat):
        print('index',i)#printing index of pattern which is found