# -*- coding: utf-8 -*-
"""sortings_calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CuaH84f7fH81IU0djMFCDCR7V9JVX8Jh
"""

ch=input()
a=int(input("enter first element"))
b=int(input("enter second element"))
match ch:
  case"+":
    print(a+b)
  case"-":
    print(a-b)
  case"*":
    print(a*b)
  case "/":
    print(a/b)
  case"//":
    print(a//b)
  case"%":
    print(a%b)

li=[]
n=int(input())
for x in range(0,n):
  y=int(input())
  li.append(y)
l=len(li)
print("Original list:",li)
def selection(li):
  for i in range(l-1):
    min=i
    for j in range(i+1,l):
      if(li[j]<li[min]):
        min=j
    li[i],li[min]=li[min],li[i]

  print("Sorted list:",li)
selection(li)

list=[]
n=int(input())
for x in range(0,n):
  ele=int(input())
  list.append(ele)
print(list)
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

    print("Sorted array:", list)

insertion_sort(list)



list=[]
n=int(input())
for x in range(0,n):
  ele=int(input())
  list.append(ele)
print(list)
l=len(list)
print("original list",list)
def BubbleSort(list):
  for i in range(0,l):
    for j in range(i+1,l):
      if(list[i]>list[j]):
        list[i],list[j]=list[j],list[i]
  print("Sorted list",list)
BubbleSort(list)