# -*- coding: utf-8 -*-
"""TNP_SC14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YXRQY8OiqUUR5Eaut6ICScauinnTCOSL
"""
class Graph:
  def __init__(self,vertices):
    self.v=vertices
    self.graph=[]
  def addEdge(self,u,v,w):
    self.graph.append([u,v,w])
  def bellmenFord(self,start):
    dict1=[float('Inf')]*self.v
    dict1[start]=0
    for _ in range(1,self.v-1):
      for u,v,w in self.graph:
        if(dict1[u]!=float('Inf')):
          if(dict1[u]+w < dict1[v]):
            dict1[v]=dict1[u]+w
    return dict1

g=Graph(7)
g.addEdge(1, 2, 6)
g.addEdge(1, 3, 5)
g.addEdge(1, 4, 5)
g.addEdge(2, 5, -1)
g.addEdge(3, 5, 1)
g.addEdge(3, 2, -2)
g.addEdge(4, 3, -2)
g.addEdge(4, 6, -1)
g.addEdge(5, 7, 3)
g.addEdge(6, 7, 3)
g.bellmenFord(1)