# -*- coding: utf-8 -*-
"""TNP_SC1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nT8pL36ux83padNfw_hBM-meZIAMEJu2
"""

ch=input()
a=int(input())
b=int(input())
match ch:
  case "+":
    print(a+b)
  case"-":
    print(a-b)
  case "*":
    print(a*b)
  case "/":
    print(a/b)
  case "//":
    print(a//b)
  case "%":
    print(a%b)
  case "**":
    print(a**b)
  case _:
    print("Invalid operator")

li=[]
n=int(input())
for x in range(0,n):
  y=int(input())
  li.append(y)
l=len(li)
print("Original list:",li)
def bubble(li):
  for i in range(0,l):
    for j in range(i+1,l):
       if(li[i]>li[j]):
          li[i],li[j]=li[j],li[i]
  print("Sorted list:",li)
bubble(li)

li=[]
n=int(input())
for x in range(0,n):
  y=int(input())
  li.append(y)
l=len(li)
print("Original list:",li)
def selection(li):
  for i in range(l-1):
    min=i
    for j in range(i+1,l):
      if(li[j]<li[min]):
        min=j
    li[i],li[min]=li[min],li[i]

  print("Sorted list:",li)
selection(li)

arr=[]
n=int(input())
for x in range(0,n):
  y=int(input())
  arr.append(y)
print("Original list:",arr)
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j+1] = arr[j]
            j-=1
        arr[j+1] = key
    print("Sorted array:", arr)
insertion_sort(arr)